spring:
  # Configuração do H2 Database para produção
  datasource:
    url: jdbc:h2:file:./data/xpe-arquitetura-prod-db
    driverClassName: org.h2.Driver
    username: sa
    password: 
  
  # Configuração do JPA/Hibernate para produção
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  
  # Configuração do H2 Console para produção (desabilitado)
  h2:
    console:
      enabled: false

# Configuração de logging para produção
logging:
  level:
    com.xpe.arquitetura: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
